
# Transformaciones políticas


```{r cargar-paquetes-3}
rm(list=ls())

library(knitr)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(elsoc)
library(lubridate)
library(viridis)
library(statar)
library(tidyverse)
```

```{r cargar-datos-3}

load(file.path('..', 'inputs', 'ELSOC_Long_2016_2022_v1.00_R.RData'))
load(file.path('..', 'inputs', 'ELSOC_Wide_2016_2022_v1.00_R.RData'))

elsoc_long.0 <- elsoc_long_2016_2022
elsoc_long_2016_2022 <- elsoc_long.0 %>%
  mutate(pleb = case_when(c55 == 4 ~ 5,
                          c55 == 1 ~ 1,
                          c55 == 2 ~ 2,
                          c55 == 3 ~ 3,
                          c55 == -999 ~ 5,
                          c55 == -888 ~ 5,
                          c55 == -777 ~ 5,
                          c55 == -666 ~ 5,
                          c56 == -999 ~ 5,
                          c56 == -888 ~ 5,
                          c56 == -777 ~ 5,
                          c56 == -666 ~ 5,
                          c56 == 2 ~ 4,
                          c57 == 1 ~ 1,
                          c57 == 2 ~ 2,
                          c57 == 3 ~ 3,
                          c57 == -999 ~ 5,
                          c57 == -888 ~ 5,
                          c57 == -777 ~ 5,
                          c57 == -666 ~ 5))  %>%  
  group_by(idencuesta) %>%
  mutate(salida = ifelse(length(na.omit(pleb)) == 0, NA, max(pleb, na.rm = T))) %>%
  ungroup()

load(file.path('..', 'inputs', 'perfiles.RData'))

elsoc_long_2016_2022 <- elsoc_long_2016_2022 %>%
  left_join(perfiles, by = "idencuesta") %>%
   mutate(pp_3 = factor(pp_3, 
                       levels = 1:3,
                       labels = c("1 (65.16%)", "2 (11.58%)", "3 (23.26%)"))) %>%
   mutate(pp_4 = factor(pp_4, 
                       levels = 1:4,
                       labels = c("Votante\nCrónico (64.24%)", "Desafecto (8.30%)", "No-Votante\nCrónico (14.28%)", "Activado (13.17%)"))) %>%
   mutate(pp_5 = factor(pp_5, 
                       levels = 1:5,
                       labels = c("1 (14.27%)", "2 (11.44%)", "3 (4.73%)", 
                                  "4 (6.33%)", "5 (63.24%)")))

elsoc_wide_2016_2022 <- elsoc_wide_2016_2022 %>%
  left_join(perfiles, by = "idencuesta") %>%
   mutate(pp_3 = factor(pp_3, 
                       levels = 1:3,
                       labels = c("1 (65.16%)", "2 (11.58%)", "3 (23.26%)"))) %>%
   mutate(pp_4 = factor(pp_4, 
                       levels = 1:4,
                       labels = c("Votante\nCrónico (64.24%)", "Desafecto (8.30%)", "No-Votante\nCrónico (14.28%)", "Activado (13.17%)"))) %>%
   mutate(pp_5 = factor(pp_5, 
                       levels = 1:5,
                       labels = c("1 (14.27%)", "2 (11.44%)", "3 (4.73%)", 
                                  "4 (6.33%)", "5 (63.24%)")))



```

## Participación electoral y proceso constituyente

```{r graf-participacion}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 & ola %in% c(1,3,5,6) &
           !is_nsnr(c11, c43, c50, c52, c54, c56)) %>% 
  prop_list(c11 == 1, c43 == 1, c50 == 1, c52 == 1, c54 == 1, c56 == 1,
            by = ola, na.rm = T) %>%
  mutate(ola = paste(name, ola)) %>%
  mutate(ola = case_when(ola == 'c11 == 1 1' ~ 1,
                          ola == 'c11 == 1 3' ~ 2,
                          ola == 'c43 == 1 5' ~ 3,
                          ola == 'c54 == 1 6' ~ 4,
                          ola == 'c50 == 1 6' ~ 5,
                          ola == 'c52 == 1 6' ~ 6,
                          ola == 'c56 == 1 6' ~ 7)) %>%
  mutate(ola = factor(ola, 
                      levels = 1:7, 
                      labels = c('Elecciones\nPresidenciales\nde 2013', 
                                 'Elecciones\nPresidenciales\nde 2017', 
                                 'Plebiscito de\nEntrada\n2020',
                                 'Convención y\nMunicipales\nde 2021',
                                 'Elecciones\nPresidenciales\nde 2021\n(1° vuelta)',
                                 'Elecciones\nPresidenciales\nde 2021\n(2° vuelta)',
                                 'Plebiscito\nSalida\n2022'))) %>% 
  ggplot(aes(y = prop, x = ola, group = 1,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_point(size = 1.75) +
  geom_line() +
  geom_text_repel(size = 3, nudge_y = .02) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Participación electoral por elección',
          subtitle = 'Porcentaje que votó en...')

```

```{r graf-pleb-salida}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  filter(ola == 6) %>%
  filter(is.na(c55)) %>%
    mutate(salida = factor(salida, 
                       levels = 1:5,
                       labels = c("Apruebo", "Rechazo", "Nulo/Blanco",
                                        "No vota", "NS/NR"))) %>% 
  prop(salida, na.rm = T) %>%
  ggplot(aes(y = prop, x = salida, label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col(fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Plebiscito de Salida 2022',
          subtitle = 'Porcentaje que votó...')
  
```

```{r graf-alluvial-pleb}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33), ola %in% 5:6 ) %>% 
      mutate(c44 = ifelse(c43 == 2,  4, c44),
             c57 = case_when(c55 == 4 ~ 6, 
                             !is.na(c55) ~ c55,
                             c56 == 2 ~ 4,
                             TRUE ~ c57),
             pos_id = ifelse(!is.na(c44), c44, c57),
             pos_id = factor(car::recode(pos_id, "6 = 5; -999:-888 = 6"),
                             levels = 1:6,
                             labels = c("Apruebo", "Rechazo", "Nulo/Blanco",
                                        "No vota", "No lo he\ndecidido", "NS/NR")),
             ola = factor(ola,
                          levels = 5:6,
                          labels = c("Plebiscito de\nEntrada\n2020",
                                     "Plebiscito de\nSalida\n2022"))) %>% 
  survey_design_elsoc() %>%
  svytable(~ pos_id + ola + idencuesta, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola) %>% 
  mutate(prop = Freq/sum(Freq, na.rm = TRUE)) %>%
  ungroup() %>% 
  filter(Freq > 0) %>%
  ggplot(aes(y = prop, x = ola, fill = fct_rev(pos_id), 
             stratum = fct_rev(pos_id), alluvium = idencuesta)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(direction = -1) +
  geom_text(data = function(x) { group_by(.data = x, ola, pos_id) %>%
      summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
      ungroup()},
            aes(label = scales::percent(prop, accuracy = .1)),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 3,
            color = c('white', 'white', 'white', 'black', 'black', 
      'white', 'white', 'white', 'black', 'black', 'black')) +
  guides(fill = guide_legend(reverse = TRUE)) +
  ggtitle('Intención de voto en plebiscito de entrada y salida')

```

```{r graf-sexo}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m0_sexo), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(m0_sexo = factor(m0_sexo, 
                       levels = 1:2,
                       labels = c("Hombre", "Mujer"))) %>%
  prop(m0_sexo, by = salida, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(salida), fill = fct_rev(m0_sexo), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'white'), 3)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Sexo según voto en plebiscito de salida')

```

```{r graf-edad}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m0_edad), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(m0_edad = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                       levels = 1:4,
                       labels = c("18-29", "30-49", "50-64", "65 o +"))) %>%
  prop(m0_edad, by = salida, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(salida), fill = fct_rev(m0_edad), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 3)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Tramos etarios según voto en plebiscito de salida')

```

```{r graf-educacion}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m01), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(m01 = factor(car::recode(m01, recodes = "1:3 = 1; 4:5 = 2; 6:7 = 3; 8:10 = 4"),
                   levels = 1:4,
                   labels = c("Básica", "Media", "Técnica", "Universitaria"))) %>%
  prop(m01, by = salida, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(salida), fill = fct_rev(m01), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 3)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Nivel educacional según voto en plebiscito de salida')

```

```{r graf-perfiles-3}

tab1 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 1) %>%
  filter(!is.na(c11), !is.na(pp_3)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_3, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 1)  

tab2 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 3) %>%
  filter(!is.na(c11), !is.na(pp_3)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_3, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 2) 

tab3 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 5) %>%
  filter(!is.na(c43), !is.na(pp_3)) %>%
  mutate(c43 = factor(car::recode(c43, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c43, by = pp_3, na.rm = T) %>% 
  rename(Participa = c43) %>% 
  mutate(var = 3) 

tab4 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c54), !is.na(pp_3)) %>%
  mutate(c54 = factor(car::recode(c54, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c54, by = pp_3, na.rm = T) %>% 
  rename(Participa = c54) %>% 
  mutate(var = 4) 

tab5 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c50), !is.na(pp_3)) %>%
  mutate(c50 = factor(car::recode(c50, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c50, by = pp_3, na.rm = T) %>% 
  rename(Participa = c50) %>% 
  mutate(var = 5) 

tab6 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c52), !is.na(pp_3)) %>%
  mutate(c52 = factor(car::recode(c52, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c52, by = pp_3, na.rm = T) %>% 
  rename(Participa = c52) %>% 
  mutate(var = 6)

tab <- rbind(tab1, tab2, tab3, tab4, tab5, tab6) %>%
  mutate(var = factor(var, levels = 1:6,
                        labels = c("Elecciones\nPresidenciales de 2013",
                                   "Elecciones\nPresidenciales de 2017",
                                   "Plebiscito de\nEntrada 2020",
                                   "Convención y Municipales\nde 2021",
                                   "Elecciones Presidenciales\nde 2021 (1° vuelta)",
                                   "Elecciones Presidenciales\nde 2021 (2° vuelta)")))
rm(tab1, tab2, tab3, tab4, tab5, tab6)

tab %>% 
  ggplot(aes(x = prop, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ pp_3) +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  theme_bw() + 
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) + 
  scale_fill_viridis_d(begin = 0, end = .8) +
  ggtitle('Perfiles de participación',
          subtitle = 'Tres clases latentes')

```

```{r graf-perfiles-4}

tab1 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 1) %>%
  filter(!is.na(c11), !is.na(pp_4)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_4, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 1)  

tab2 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 3) %>%
  filter(!is.na(c11), !is.na(pp_4)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_4, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 2) 

tab3 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 5) %>%
  filter(!is.na(c43), !is.na(pp_4)) %>%
  mutate(c43 = factor(car::recode(c43, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c43, by = pp_4, na.rm = T) %>% 
  rename(Participa = c43) %>% 
  mutate(var = 3) 

tab4 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c54), !is.na(pp_4)) %>%
  mutate(c54 = factor(car::recode(c54, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c54, by = pp_4, na.rm = T) %>% 
  rename(Participa = c54) %>% 
  mutate(var = 4) 

tab5 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c50), !is.na(pp_4)) %>%
  mutate(c50 = factor(car::recode(c50, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c50, by = pp_4, na.rm = T) %>% 
  rename(Participa = c50) %>% 
  mutate(var = 5) 

tab6 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c52), !is.na(pp_4)) %>%
  mutate(c52 = factor(car::recode(c52, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c52, by = pp_4, na.rm = T) %>% 
  rename(Participa = c52) %>% 
  mutate(var = 6)

tab <- rbind(tab1, tab2, tab3, tab4, tab5, tab6) %>%
  mutate(var = factor(var, levels = 1:6,
                        labels = c("Elecciones\nPresidenciales de 2013",
                                   "Elecciones\nPresidenciales de 2017",
                                   "Plebiscito de\nEntrada 2020",
                                   "Convención y Municipales\nde 2021",
                                   "Elecciones Presidenciales\nde 2021 (1° vuelta)",
                                   "Elecciones Presidenciales\nde 2021 (2° vuelta)")))
rm(tab1, tab2, tab3, tab4, tab5, tab6)

tab %>% 
  ggplot(aes(x = prop, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ pp_4) +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  theme_bw() + 
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) + 
  scale_fill_viridis_d(begin = 0, end = .8) +
  ggtitle('Perfiles de participación',
          subtitle = 'Cuatro clases latentes')

```

```{r graf-perfiles-5}

tab1 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 1) %>%
  filter(!is.na(c11), !is.na(pp_5)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_5, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 1)  

tab2 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 3) %>%
  filter(!is.na(c11), !is.na(pp_5)) %>%
  mutate(c11 = factor(car::recode(c11, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c11, by = pp_5, na.rm = T) %>% 
  rename(Participa = c11) %>% 
  mutate(var = 2) 

tab3 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 5) %>%
  filter(!is.na(c43), !is.na(pp_5)) %>%
  mutate(c43 = factor(car::recode(c43, "1 = 2; 2:3 = 1"),
                             levels = 1:2,
                             labels = c('No votó', 'Votó'))) %>%
  prop(c43, by = pp_5, na.rm = T) %>% 
  rename(Participa = c43) %>% 
  mutate(var = 3) 

tab4 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c54), !is.na(pp_5)) %>%
  mutate(c54 = factor(car::recode(c54, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c54, by = pp_5, na.rm = T) %>% 
  rename(Participa = c54) %>% 
  mutate(var = 4) 

tab5 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c50), !is.na(pp_5)) %>%
  mutate(c50 = factor(car::recode(c50, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c50, by = pp_5, na.rm = T) %>% 
  rename(Participa = c50) %>% 
  mutate(var = 5) 

tab6 <- elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33)) %>% 
  filter(ola == 6) %>%
  filter(!is.na(c52), !is.na(pp_5)) %>%
  mutate(c52 = factor(car::recode(c52, "1 = 2; 2 = 1"),
                          levels = 1:2,
                          labels = c('No votó', 'Votó'))) %>%
  prop(c52, by = pp_5, na.rm = T) %>% 
  rename(Participa = c52) %>% 
  mutate(var = 6)

tab <- rbind(tab1, tab2, tab3, tab4, tab5, tab6) %>%
  mutate(var = factor(var, levels = 1:6,
                        labels = c("Elecciones\nPresidenciales de 2013",
                                   "Elecciones\nPresidenciales de 2017",
                                   "Plebiscito de\nEntrada 2020",
                                   "Convención y Municipales\nde 2021",
                                   "Elecciones Presidenciales\nde 2021 (1° vuelta)",
                                   "Elecciones Presidenciales\nde 2021 (2° vuelta)")))
rm(tab1, tab2, tab3, tab4, tab5, tab6)

tab %>% 
  ggplot(aes(x = prop, y = var, fill = Participa)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  facet_grid(~ pp_5) +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  theme_bw() + 
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) + 
  scale_fill_viridis_d(begin = 0, end = .8) +
  ggtitle('Perfiles de participación',
          subtitle = 'Cinco clases latentes')

```

```{r graf-sexo-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m0_sexo), !is.na(pp_4)) %>%   
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(m0_sexo = factor(m0_sexo, 
                       levels = 1:2,
                       labels = c("Hombre", "Mujer"))) %>%
  prop(m0_sexo, by = pp_4, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(pp_4), fill = fct_rev(m0_sexo), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Sexo según tipo de votante')

```

```{r graf-edad-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m0_edad), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(m0_edad = factor(car::recode(m0_edad, "18:29 = 1; 30:49 = 2; 50:64 = 3; 65:150 = 4"),
                       levels = 1:4,
                       labels = c("18-29", "30-49", "50-64", "65 o +"))) %>%
  prop(m0_edad, by = pp_4, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(pp_4), fill = fct_rev(m0_edad), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Tramos etarios según tipo de votante')

```

```{r graf-educacion-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(m01), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(m01 = factor(car::recode(m01, recodes = "1:3 = 1; 4:5 = 2; 6:7 = 3; 8:10 = 4"),
                   levels = 1:4,
                   labels = c("Básica", "Media", "Técnica", "Universitaria"))) %>%
  prop(m01, by = pp_4, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(pp_4), fill = fct_rev(m01), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Nivel educacional según tipo de votante')

```

```{r graf-tipo-salida}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(salida), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(salida, by = pp_4, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(pp_4), fill = fct_rev(salida), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'white', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de salida según tipo de votante')

```

```{r graf-alluvial-pleb-tipo}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33), ola %in% 5:6 ) %>% 
      mutate(c44 = ifelse(c43 == 2,  4, c44),
             c57 = case_when(c55 == 4 ~ 6, 
                             !is.na(c55) ~ c55,
                             c56 == 2 ~ 4,
                             TRUE ~ c57),
             pos_id = ifelse(!is.na(c44), c44, c57),
             pos_id = factor(car::recode(pos_id, "6 = 5; -999:-888 = 6"),
                             levels = 1:6,
                             labels = c("Apruebo", "Rechazo", "Nulo/Blanco",
                                        "No vota", "No lo he\ndecidido", "NS/NR")),
             ola = factor(ola,
                          levels = 5:6,
                          labels = c("Plebiscito de\nEntrada\n2020",
                                     "Plebiscito de\nSalida\n2022"))) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante Crónico", "Desafecto", "No-Votante Crónico", "Activado"))) %>%
  survey_design_elsoc() %>%
  svytable(~ pos_id + ola + idencuesta + pp_4, design = .) %>% 
  as.data.frame() %>% 
  group_by(ola, pp_4) %>% 
  mutate(prop = Freq/sum(Freq, na.rm = TRUE)) %>%
  ungroup() %>% 
  filter(Freq > 0) %>%
  ggplot(aes(y = prop, x = ola, fill = fct_rev(pos_id), 
             stratum = fct_rev(pos_id), alluvium = idencuesta)) +
  theme_bw() +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0, width = .55) +
  scale_y_continuous(labels = scales::percent) + 
  facet_wrap(~ pp_4) +
  ylab(label = NULL) +
  xlab(label = NULL) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  scale_fill_viridis_d(direction = -1) +
  geom_text(data = function(x) { group_by(.data = x, ola, pos_id, pp_4) %>%
      summarise(prop = sum(prop, na.rm = TRUE), idencuesta = 1) %>%
      ungroup()},
            aes(label = scales::percent(prop, accuracy = .1)),
            position = position_stack(vjust = .5),
            show.legend = FALSE,
            size = 3,
            color = 'white') +
  guides(fill = guide_legend(reverse = TRUE)) +
  ggtitle('Intención de voto en plebiscito de entrada y salida')

```

```{r consti-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c28)) %>%
  mutate(c28 = factor(car::recode(c28, "1:2 = 1; 3 = 2; 4:5 = 3"), 
                      levels = 1:3,
                      labels = c("En desacuerdo o\ntotalmente en desacuerdo",
                                 "Ni de acuerdo\nni en desacuerdo", 
                                 "De acuerdo o\ntotalmente de acuerdo"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c28, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c28), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 4)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Nueva constitución según ola')

```

```{r graf-consti}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c28), !is.na(salida)) %>%  
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c28 %in% 4:5, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Nueva constitución según voto en plebiscito de salida',
          subtitle = 'De acuerdo o muy de acuerdo con cambiar la constitución')

```

```{r graf-consti-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c28), !is.na(pp_4)) %>%  
    mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c28 %in% 4:5, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Nueva constitución según tipo de votante',
          subtitle = 'De acuerdo o muy de acuerdo con cambiar la constitución')

```

```{r graf-convencion}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 & ola %in% c(1,3,5,6) &
           !is_nsnr(c05_14, salida), !is.na(salida)) %>% 
  prop_list(c05_14 %in% 4:5, by = salida, na.rm = T) %>%
  mutate(salida = factor(salida, 
                       levels = 1:5,
                       labels = c("Apruebo", "Rechazo", "Nulo/Blanco",
                                        "No vota", "NS/NR")))%>% 
  ggplot(aes(y = prop, x = salida, label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col(fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,.1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en la Convención Constitucional según voto en plebiscito de salida',
          subtitle = 'Bastante o mucha confianza')

```

```{r graf-convencion-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 & ola %in% c(1,3,5,6) &
           !is_nsnr(c05_14, pp_4), !is.na(pp_4)) %>% 
  prop_list(c05_14 %in% 4:5, by = pp_4, na.rm = T) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  ggplot(aes(y = prop, x = pp_4, label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_col(fill = viridis(1, begin = .33)) +
  geom_text(position = position_dodge(.9), vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,.1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en la Convención Constitucional según tipo de votante',
          subtitle = 'Bastante o mucha confianza')

```

## Actitudes hacia la democracia

```{r leg-dem-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c25)) %>%
  mutate(c25 = factor(c25, 
                      levels = 1:3,
                      labels = c("La democracia es preferible\na cualquier otra forma\nde gobierno",
                                 "En algunas circunstancias,\nun gobierno autoritario\npuede ser preferible", 
                                 "A la gente como uno,\nnos da lo mismo"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c25, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c25), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Legitimidad democrática según ola')

```

```{r graf-leg-dem}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c25), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c25 == 1, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Legitimidad democrática, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que prefiere la democracia a cualquier otra forma de gobierno')


```

```{r graf-leg-dem-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c25), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c25 == 1, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Legitimidad democrática, según tipo de votante',
          subtitle = 'Porcentaje que prefiere la democracia a cualquier otra forma de gobierno')


```

```{r satis-dem-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c01)) %>%
  mutate(c01 = factor(car::recode(c01, "1:2 = 1; 3 = 2; 4:5 = 3"), 
                      levels = 1:3,
                      labels = c("Nada o\npoco satisfecho",
                                 "Algo satisfecho", 
                                 "Bastante o\nmuy satisfecho"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c01, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c01), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Satisfacción democrática según ola')

```

```{r graf-satis-dem}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c01), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c01 %in% 4:5, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Satisfacción democrática, según voto en plebiscito de salida',
          subtitle = 'Bastante o muy satisfecho')


```

```{r graf-satis-dem-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c01), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c01 %in% 4:5, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Satisfacción democrática, según tipo de votante',
          subtitle = 'Bastante o muy satisfecho')


```

```{r autoritarismo-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c18_04), !is.na(c18_05), !is.na(c18_06), !is.na(c18_07)) %>%
  dplyr::select(c18_04, c18_05, c18_06, c18_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c18_04, c18_05, c18_06, c18_07)) %>%
  mutate(name = factor(name,
                       levels = c('c18_04', 'c18_05', 'c18_06', 'c18_07'),
                       labels = c(' Lo que este país\nnecesita es\nun gobierno firme',
                                  ' Lo que nuestro\npaís necesita es\nun mandatario/a fuerte',
                                  ' La obediencia y el\nrespeto por\nla autoridad son los valores\nmás importantes',
                                  ' Las verdaderas claves\npara tener\nuna buena vida son\nla obediencia y la disciplina'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes autoritarias, según ola',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-autoritarismo}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c18_04), !is.na(c18_05), !is.na(c18_06), !is.na(c18_07)) %>%
  dplyr::select(c18_04, c18_05, c18_06, c18_07, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c18_04, c18_05, c18_06, c18_07)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c18_04', 'c18_05', 'c18_06', 'c18_07'),
                       labels = c(' En vez de tanta preocupación\npor los derechos de las personas,\nlo que este país necesita es un gobierno firme',
                                  ' Lo que nuestro país necesita es un mandatario/a fuerte\ncon la determinación para\nllevarnos por el camino correcto',
                                  ' La obediencia y el respeto por\nla autoridad son los valores más importantes\nque los niños debieran aprender',
                                  ' Las verdaderas claves para tener\nuna buena vida son la obediencia y la disciplina'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes autoritarias, según voto en plebiscito de salida',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-autoritarismo-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c18_04), !is.na(c18_05), !is.na(c18_06), !is.na(c18_07)) %>%
  dplyr::select(c18_04, c18_05, c18_06, c18_07, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c18_04, c18_05, c18_06, c18_07)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c18_04', 'c18_05', 'c18_06', 'c18_07'),
                       labels = c(' En vez de tanta preocupación\npor los derechos de las personas,\nlo que este país necesita es un gobierno firme',
                                  ' Lo que nuestro país necesita es un mandatario/a fuerte\ncon la determinación para\nllevarnos por el camino correcto',
                                  ' La obediencia y el respeto por\nla autoridad son los valores más importantes\nque los niños debieran aprender',
                                  ' Las verdaderas claves para tener\nuna buena vida son la obediencia y la disciplina'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes autoritarias, según tipo de votante',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

## Identidad e involucramiento político

```{r posicion-pol-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c15)) %>%
  mutate(c15 = factor(car::recode(c15, "0:4 = 1; 5 = 2; 6:10 = 3; 11 = 4; 12 = 5"), 
                       levels = 1:5,
                       labels = c("Izquierda", "Centro", "Derecha",
                                  "Independiente", "Ninguna"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c15, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c15), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'black', 'black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Pocisión política según ola')

```

```{r graf-posicion-pol}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(c15), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(c15 = factor(car::recode(c15, "0:4 = 1; 5 = 2; 6:10 = 3; 11 = 4; 12 = 5"), 
                       levels = 1:5,
                       labels = c("Izquierda", "Centro", "Derecha",
                                  "Independiente", "Ninguna"))) %>%
  prop(c15, by = salida, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(salida), fill = fct_rev(c15), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white', 'white'), 3)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Posición política 2022, según voto en plebiscito de salida',
          subtitle = 'Autoposicionamiento político en la escala izquierda-derecha')

```

```{r graf-posicion-pol-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33 | ola == 6) %>% 
  filter(!is.na(c15), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(c15 = factor(car::recode(c15, "0:4 = 1; 5 = 2; 6:10 = 3; 11 = 4; 12 = 5"), 
                       levels = 1:5,
                       labels = c("Izquierda", "Centro", "Derecha",
                                  "Independiente", "Ninguna"))) %>%
  prop(c15, by = pp_4, na.rm = TRUE) %>% 
  ggplot(aes(x = prop, y = fct_rev(pp_4), fill = fct_rev(c15), 
             label = scales::percent(prop, .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Posición política 2022, según tipo de votante',
          subtitle = 'Autoposicionamiento político en la escala izquierda-derecha')

```

```{r graf-centro}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c15), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c15 == 5, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Posición política de centro, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que se autoidentifica de centro')


```

```{r graf-centro-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c15), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c15 == 5, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Posición política de centro, según tipo de votante',
          subtitle = 'Porcentaje que se autoidentifica de centro')


```

```{r graf-sin-posicion}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c15), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c15 == 12, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Ausencia de posición política, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que no se autoidentifica en la escala izquierda-derecha')


```

```{r graf-sin-posicion-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c15), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c15 == 12, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Ausencia de posición política, según tipo de votante',
          subtitle = 'Porcentaje que no se autoidentifica en la escala izquierda-derecha')


```

```{r interes-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c13)) %>%
  mutate(c13 = factor(car::recode(c13, "1:2 = 1; 3 = 2; 4:5 = 3"), 
                       levels = 1:3,
                       labels = c("Nada o\npoco interesado", 
                                  "Algo\ninteresado", 
                                  "Batsatante o\nmuy interesado"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c13, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c13), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Interés en la política según ola')

```

```{r graf-interes}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c13), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c13 %in% 4:5, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Interés en la política, según voto en plebiscito de salida',
          subtitle = 'Bastante o muy interesado')

```

```{r graf-interes-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c13), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c13 %in% 4:5, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Interés en la política, según tipo de votante',
          subtitle = 'Bastante o muy interesado')

```

```{r partido-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c13)) %>%
  mutate(c13 = factor(car::recode(c13, "1 = 1; 2:3 = 2"), 
                       levels = 1:2,
                       labels = c("Miembro activo\n o inactivo", 
                                  "No miembro"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c13, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c13), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Membresía con un partido político según ola')

```

```{r graf-partido}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c12_03), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c12_03 %in% 2:3, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.25)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Partidismo, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que es miembro de un partido o movimiento político')

```

```{r graf-partido-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c12_03), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c12_03 %in% 2:3, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Partidismo, según tipo de votante',
          subtitle = 'Porcentaje que es miembro de un partido o movimiento político')

```

```{r id-partido-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c16)) %>%
  mutate(c16 = factor(car::recode(c16, "15 = 1; 1:14 = 2; 16:19 = 2"), 
                       levels = 1:2,
                       labels = c("No se\nidentifica", 
                                  "Se identifica\ncon un partido"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c16, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c16), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white'), 5)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Partidismo según ola')

```

```{r graf-id-partido}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c16), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c16 == 15, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Partidismo, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que no se identifica con ningún partido político')

```

```{r graf-id-partido-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c16), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c16 == 15, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Partidismo, según tipo de votante',
          subtitle = 'Porcentaje que no se identifica con ningún partido político')

```

```{r involv-pol-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c14_01), !is.na(c14_02), !is.na(c08_04)) %>%
  dplyr::select(c14_01, c14_02, c08_04, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c14_01, c14_02, c08_04)) %>% 
  mutate(name = factor(name,
                       levels = c('c14_01', 'c14_02', 'c08_04'),
                       labels = c('Habla de politica\ncon familiares o amigos',
                                  'Se informa sobre politica\nen medios de comunicacion',
                                  'Usa redes sociales para\nopinar en temas publicos'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>%  
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Involucramiento político, según ola',
          subtitle = 'Frecuente o muy frecuentemente' )


```

```{r graf-involv-poli}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c14_01), !is.na(c14_02), !is.na(c08_04)) %>%
  dplyr::select(c14_01, c14_02, c08_04, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c14_01, c14_02, c08_04)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c14_01', 'c14_02', 'c08_04'),
                       labels = c('Habla de politica\ncon familiares o amigos',
                                  'Se informa sobre politica\nen medios de comunicacion',
                                  'Usa redes sociales para\nopinar en temas publicos'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Involucramiento político, según voto en plebiscito de salida',
          subtitle = 'Frecuente o muy frecuentemente' )


```

```{r graf-involv-poli-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c14_01), !is.na(c14_02), !is.na(c08_04)) %>%
  dplyr::select(c14_01, c14_02, c08_04, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c14_01, c14_02, c08_04)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c14_01', 'c14_02', 'c08_04'),
                       labels = c('Habla de politica\ncon familiares o amigos',
                                  'Se informa sobre politica\nen medios de comunicacion',
                                  'Usa redes sociales para\nopinar en temas publicos'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Involucramiento político, según tipo de votante',
          subtitle = 'Frecuente o muy frecuentemente' )


```

## Confianza institucional

```{r conf-pol-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_01), !is.na(c05_02), !is.na(c05_07), !is.na(c05_08)) %>%
  dplyr::select(c05_01, c05_02, c05_07, c05_08, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c05_01, c05_02, c05_07, c05_08)) %>% 
  mutate(name = factor(name,
                       levels = c('c05_01', 'c05_02', 'c05_07', 'c05_08'),
                       labels = c('Gobierno',
                                  'Partidos políticos',
                                  'Congreso',
                                  'Presidente'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones políticas, según ola',
          subtitle = 'Bastante o mucha confianza' )


```

```{r graf-conf-pol}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_01), !is.na(c05_02), !is.na(c05_07), !is.na(c05_08)) %>%
  dplyr::select(c05_01, c05_02, c05_07, c05_08, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c05_01, c05_02, c05_07, c05_08)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c05_01', 'c05_02', 'c05_07', 'c05_08'),
                       labels = c('Gobierno',
                                  'Partidos políticos',
                                  'Congreso',
                                  'Presidente'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones políticas, según voto en plebiscito de salida',
          subtitle = 'Bastante o mucha confianza' )

```

```{r graf-conf-pol-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_01), !is.na(c05_02), !is.na(c05_07), !is.na(c05_08)) %>%
  dplyr::select(c05_01, c05_02, c05_07, c05_08, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c05_01, c05_02, c05_07, c05_08)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c05_01', 'c05_02', 'c05_07', 'c05_08'),
                       labels = c('Gobierno',
                                  'Partidos políticos',
                                  'Congreso',
                                  'Presidente'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones políticas, según tipo de votante',
          subtitle = 'Bastante o mucha confianza' )

```

```{r conf-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_03), !is.na(c05_05)) %>%
  dplyr::select(c05_03, c05_05, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c05_03, c05_05)) %>% 
  mutate(name = factor(name,
                       levels = c('c05_03', 'c05_05'),
                       labels = c('Carabineros',
                                  'Poder Judicial'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones, según ola',
          subtitle = 'Bastante o mucha confianza' )


```

```{r graf-conf-inst}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_03), !is.na(c05_05)) %>%
  dplyr::select(c05_03, c05_05, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c05_03, c05_05)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c05_03', 'c05_05'),
                       labels = c('Carabineros',
                                  'Poder Judicial'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones, según voto en plebiscito de salida',
          subtitle = 'Bastante o mucha confianza' )

```

```{r graf-conf-inst-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c05_03), !is.na(c05_05)) %>%
  dplyr::select(c05_03, c05_05, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c05_03, c05_05)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c05_03', 'c05_05'),
                       labels = c('Carabineros',
                                  'Poder Judicial'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Confianza en instituciones, según tipo de votante',
          subtitle = 'Bastante o mucha confianza' )

```

## Movilización social

```{r graf-mov-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c20)) %>%
  mutate(movsoc = car::recode(c20, "1:5 = 1; 8:10 = 1; 6:7 = 2; 11:12 = 3"),
       movsoc = factor(movsoc, levels = 1:3,
                       labels = c('Mov. sociales progresistas', 'Mov. sociales conservadores', 'Ninguno'))) %>%
  prop(movsoc, by = c(ola), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = movsoc, group = movsoc,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Valoración de movimientos sociales, según ola',
          subtitle = 'Tipo de movimiento social más valorado' )

```

```{r graf-mov-tipo}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c20)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(movsoc = car::recode(c20, "1:5 = 1; 8:10 = 1; 6:7 = 2; 11:12 = 3"),
       movsoc = factor(movsoc, levels = 1:3,
                       labels = c('Mov. sociales progresistas', 'Mov. sociales conservadores', 'Ninguno'))) %>%
  prop(movsoc, by = c(salida, ola), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ movsoc) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Valoración de movimientos sociales, según voto en plebiscito de salida',
          subtitle = 'Tipo de movimiento social más valorado' )

```

```{r graf-mov-tipo-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c20)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(movsoc = car::recode(c20, "1:5 = 1; 8:10 = 1; 6:7 = 2; 11:12 = 3"),
       movsoc = factor(movsoc, levels = 1:3,
                       labels = c('Mov. sociales progresistas', 'Mov. sociales conservadores', 'Ninguno'))) %>%
  prop(movsoc, by = c(pp_4, ola), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ movsoc) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Valoración de movimientos sociales, según tipo de votante',
          subtitle = 'Tipo de movimiento social más valorado' )

```

```{r parti-mov-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  filter(!is.na(c08_02)) %>%
  mutate(c08_02 = factor(car::recode(c08_02, "1:2 = 1; 3 = 2; 4:5 = 3"), 
                       levels = 1:3,
                       labels = c("Nunca o\ncasi nunca", 
                                  "A veces",
                                  "Frecuente o\nmuy frecuentemente"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = c08_02, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c08_02), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_y_continuous(labels = scales::percent) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .8) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
  ggtitle('Participación en marchas o manifestaciones según ola')

```

```{r graf-parti-mov}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c08_02), !is.na(salida)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c08_02 %in% 4:5, by = c(ola, salida), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Participación en marchas o manifestaciones, según voto en plebiscito de salida',
          subtitle = 'Frecuente o muy frecuentemente')

```

```{r graf-parti-mov-2}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>% 
  as_label(ola) %>%
  filter(!is.na(c08_02), !is.na(pp_4)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  prop(c08_02 %in% 4:5, by = c(ola, pp_4), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .025, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.2)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Participación en marchas o manifestaciones, según tipo de votante',
          subtitle = 'Frecuente o muy frecuentemente')

```

## Opinión pública y contingencia

```{r op-valores-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_01), !is.na(c37_02)) %>%
  dplyr::select(c37_01, c37_02,  ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c37_01, c37_02)) %>% 
  mutate(name = factor(name,
                       levels = c('c37_01', 'c37_02'),
                       labels = c('Las parejas homosexuales deberían\npoder adoptar hijos',
                                  'El aborto debe ser legal bajo\ncualquier circunstancia'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes valóricas, según ola',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-op-valores}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_01), !is.na(c37_02)) %>%
  dplyr::select(c37_01, c37_02,  ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c37_01, c37_02)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c37_01', 'c37_02'),
                       labels = c('Las parejas homosexuales deberían\npoder adoptar hijos',
                                  'El aborto debe ser legal bajo\ncualquier circunstancia'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .7)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes valóricas, según voto en plebiscito de salida',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-op-valores-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_01), !is.na(c37_02)) %>%
  dplyr::select(c37_01, c37_02,  ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c37_01, c37_02)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c37_01', 'c37_02'),
                       labels = c('Las parejas homosexuales deberían\npoder adoptar hijos',
                                  'El aborto debe ser legal bajo\ncualquier circunstancia'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .6)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Actitudes valóricas, según tipo de votante',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r op-contingente-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_03), !is.na(c37_04), !is.na(c37_05)) %>%
  dplyr::select(c37_03, c37_04, c37_05,  ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c37_03, c37_04, c37_05)) %>% 
  mutate(name = factor(name,
                       levels = c('c37_03', 'c37_04', 'c37_05'),
                       labels = c('El Estado de Chile, más que\nlos privados, debería ser el principal\nproveedor de educación',
                                  'Cada persona debiera asegurarse\npor si mismo su futura pensión\npara la tercera edad',
                                  'Chile debería tomar medidas más\ndrásticas para impedir el ingreso\nde inmigrantes al país'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Opinón pública sobre temas contingentes, según ola',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-op-contingente}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_03), !is.na(c37_04), !is.na(c37_05)) %>%
  dplyr::select(c37_03, c37_04, c37_05,  ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(c37_03, c37_04, c37_05)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('c37_03', 'c37_04', 'c37_05'),
                       labels = c('El Estado de Chile, más que\nlos privados, debería ser el principal\nproveedor de educación',
                                  'Cada persona debiera asegurarse\npor si mismo su futura pensión\npara la tercera edad',
                                  'Chile debería tomar medidas más\ndrásticas para impedir el ingreso\nde inmigrantes al país'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Opinón pública sobre temas contingentes, según voto en plebiscito de salida',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

```{r graf-op-contingente-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(c37_03), !is.na(c37_04), !is.na(c37_05)) %>%
  dplyr::select(c37_03, c37_04, c37_05,  ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(c37_03, c37_04, c37_05)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('c37_03', 'c37_04', 'c37_05'),
                       labels = c('El Estado de Chile, más que\nlos privados, debería ser el principal\nproveedor de educación',
                                  'Cada persona debiera asegurarse\npor si mismo su futura pensión\npara la tercera edad',
                                  'Chile debería tomar medidas más\ndrásticas para impedir el ingreso\nde inmigrantes al país'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Opinón pública sobre temas contingentes, según tipo de votante',
          subtitle = 'De acuerdo o totalmente de acuerdo' )


```

## Justificación de la violencia

```{r graf-justviolencia1-ola-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_02), !is.na(f05_01)) %>%
  dplyr::select(f05_01, f05_02, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(f05_01, f05_02)) %>%
  mutate(name = factor(name,
                       levels = c('f05_01', 'f05_02'),
                       labels = c('Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto',
                                  'Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia a manos de ciudadanos, según ola',
          subtitle = 'Muchas veces o siempre se justifica' )


```

```{r graf-justviolencia1-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_02), !is.na(f05_01)) %>%
  dplyr::select(f05_01, f05_02, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(f05_01, f05_02)) %>% 
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('f05_01', 'f05_02'),
                       labels = c('Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto',
                                  'Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia a manos de ciudadanos, según voto en plebiscito de salida',
          subtitle = 'Muchas veces o siempre se justifica' )


```

```{r graf-justviolencia1-ola-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_02), !is.na(f05_01)) %>%
  dplyr::select(f05_01, f05_02, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(f05_01, f05_02)) %>% 
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('f05_01', 'f05_02'),
                       labels = c('Personas persigan y golpeen a un delincuente\n que acaba de cometer un asalto',
                                  'Personas amarren a un poste y desnuden a un\n delincuente que acaba de cometer un asalto'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia a manos de ciudadanos, según tipo de votante',
          subtitle = 'Muchas veces o siempre se justifica' )


```

```{r graf-justviolencia2-ola-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_03), !is.na(f05_04), !is.na(f05_07)) %>%
  dplyr::select(f05_03, f05_04, f05_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(f05_03, f05_04, f05_07)) %>%
  mutate(name = factor(name,
                       levels = c('f05_03', 'f05_04', 'f05_07'),
                       labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                  'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                  'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>%
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .3)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, nudge_y = .02, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia, según ola',
          subtitle = 'Muchas veces o siempre se justifica' )


```

```{r graf-justviolencia2-ola}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_03), !is.na(f05_04), !is.na(f05_07)) %>%
  dplyr::select(f05_03, f05_04, f05_07, ola, ponderador02, segmento_disenno, estrato_disenno, salida) %>% 
  pivot_longer(cols = c(f05_03, f05_04, f05_07)) %>%
  mutate(salida = factor(car::recode(salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  mutate(name = factor(name,
                       levels = c('f05_03', 'f05_04', 'f05_07'),
                       labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                  'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                  'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>%
  prop(value %in% 4:5, by = c(salida, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(salida)) %>%
  ggplot(aes(y = prop, x = ola, color = salida, group = salida,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .25)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia, según voto en plebiscito de salida',
          subtitle = 'Muchas veces o siempre se justifica' )

```


```{r graf-justviolencia2-ola-2}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion == 1 | tipo_atricion == 33) %>%
  as_label(ola) %>%
  filter(!is.na(f05_03), !is.na(f05_04), !is.na(f05_07)) %>%
  dplyr::select(f05_03, f05_04, f05_07, ola, ponderador02, segmento_disenno, estrato_disenno, pp_4) %>% 
  pivot_longer(cols = c(f05_03, f05_04, f05_07)) %>%
  mutate(pp_4 = factor(pp_4,
                       labels = c("Votante\nCrónico", "Desafecto", "No-Votante\nCrónico", "Activado"))) %>%
  mutate(name = factor(name,
                       levels = c('f05_03', 'f05_04', 'f05_07'),
                       labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                  'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                  'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>%
  prop(value %in% 4:5, by = c(pp_4, ola, name), na.rm = TRUE) %>% 
  filter(!is.na(pp_4)) %>%
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  facet_wrap(~ name) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .25)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .0, end = .8, option = 'viridis') + 
  geom_text_repel(size = 3, color = "black") +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Justificación de la violencia, según tipo de votante',
          subtitle = 'Muchas veces o siempre se justifica' )

```

