
# Cohesión socio-territorial


```{r cargar-paquetes-4, include = FALSE}

library(knitr)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
library(elsoc)
library(lubridate)
library(viridis)
library(statar)

```


```{r cargar-datos-4, include = FALSE}

load(file.path('..', 'inputs', 'ELSOC_Long_2016_2022_v1.00_R.RData'))
load(file.path('..', 'inputs', 'ELSOC_Wide_2016_2022_v1.00_R.RData'))

# Voto en plebiscito de salida para agregar a toda la muestra:
voto_salida <- elsoc_long_2016_2022 %>% 
  filter(ola == 6) %>% 
  mutate(voto_salida = case_when(c55 == 4 ~ 5,
                                 c55 %in% 1:3 ~ c55,
                                 c55 %in% -666:-999 ~ 5,
                                 c56 %in% -666:-999 ~ 5,
                                 c56 == 2 ~ 4,
                                 c57 %in% 1:3 ~ c57,
                                 c57 %in% -666:-999 ~ 5
                          ))  %>%
  select(idencuesta, voto_salida)

# Cargar datos de perfiles:
load(file.path('..', 'inputs', 'perfiles.RData'))
perfiles0 <- perfiles

perfiles <- perfiles0 %>%
   mutate(pp_3 = factor(pp_3, 
                       levels = 1:3,
                       labels = c("1 (65.16%)", "2 (11.58%)", "3 (23.26%)"))) %>%
   mutate(pp_4 = factor(pp_4, 
                       levels = 1:4,
                       labels = c("Votante\nCrónico (64.24%)", "Desafecto (8.30%)", "No-Votante\nCrónico (14.28%)", "Activado (13.17%)"))) %>%
   mutate(pp_5 = factor(pp_5, 
                       levels = 1:5,
                       labels = c("1 (14.27%)", "2 (11.44%)", "3 (4.73%)", 
                                  "4 (6.33%)", "5 (63.24%)")))


```




```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  filter(!is.na(t10), tipo_atricion %in% c(1, 33), ola == 6) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(voto_salida, by = zona, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona, fill = fct_rev(voto_salida),
             label = scales::percent(prop, accuracy = .1))) +
  geom_col(position = 'stack') +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_y_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'white', 'white'), 4)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de salida, según zona geográfica')
  
```



```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  filter(!is.na(t10), tipo_atricion %in% c(1, 33), ola == 6) %>%  
  mutate(post_plebiscito = factor(!is.na(c56), 
                                  levels = c(TRUE, FALSE),
                                  labels = c('Muestra Pre-plebiscito', 'Muestra Post-plebiscito')),
    voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(voto_salida, by = c(zona, post_plebiscito), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona, fill = fct_rev(voto_salida),
             label = scales::percent(prop, accuracy = .1))) +
  geom_col(position = 'stack') +
  facet_wrap(~post_plebiscito) +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_y_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'white', 'white'), 8)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de salida, según zona geográfica')
  
```
```{r}


elsoc_long_2016_2022 %>%
  left_join(perfiles, by = 'idencuesta') %>% 
  filter(!is.na(pp_4), tipo_atricion %in% c(1, 33)) %>% 
  mutate(post_plebiscito = factor(!is.na(c56), 
                                  levels = c(TRUE, FALSE),
                                  labels = c('Muestra Pre-plebiscito', 'Muestra Post-plebiscito')),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(pp_4, by = c(zona, post_plebiscito), na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = zona, fill = fct_rev(pp_4),
             label = scales::percent(prop, accuracy = .1))) +
  geom_col(position = 'stack') +
  facet_wrap(~post_plebiscito) +
  labs(y = NULL, x = NULL, title = NULL, fill = NULL) +
  scale_y_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), size = 3,
            color = rep(c('black', 'black', 'white', 'white'), 8)) +
  theme_bw() + 
  scale_fill_viridis_d(begin = 0, end = .8, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Voto en plebiscito de salida, según zona geográfica')
  
```


```{r}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion %in% c(1, 33), ola == 6) %>%  
  mutate(post_plebiscito = factor(!is.na(c56), 
                                  levels = c(TRUE, FALSE),
                                  labels = c('Muestra Pre-plebiscito', 'Muestra Post-plebiscito')),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(zona, by = c(post_plebiscito), na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = zona, fill = post_plebiscito,
             label = scales::percent(prop, accuracy = .1))) +
  geom_col(position = 'dodge2') +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) 
  
```

```{r}

elsoc_long_2016_2022 %>%
  filter(tipo_atricion %in% c(1, 33), ola == 6) %>%  
  mutate(post_plebiscito = factor(!is.na(c56), 
                                  levels = c(TRUE, FALSE),
                                  labels = c('Muestra Pre-plebiscito', 
                                             'Muestra Post-plebiscito'))) %>%
  sjlabelled::as_label(estrato) %>% 
  prop(estrato, by = c(post_plebiscito), na.rm = TRUE) %>%
  ggplot(aes(y = prop, x = estrato, fill = post_plebiscito,
             label = scales::percent(prop, accuracy = .1))) +
  geom_col(position = 'dodge2') +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) 

  
```




### Conflicto territorial y seguridad

#### Conflicto barrial


```{r confli-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(t11_01, t11_02, t11_03, t11_04)) %>% 
  mutate(barrio_confli = (t11_01 + t11_02 + t11_03 + t11_04)/4,
         barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0, 1, 2.75, 5)),
         labels = c("Nunca", "Pocas o algunas veces", "Muchas veces o siempre"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = barrio_confli_rec, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(barrio_confli_rec), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  ggtitle(label = 'Conflictos barriales, según ola',
          subtitle = 'Porcentaje que presenta Molestia o incomodidad por problemas con sus vecinos') +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank())

```


```{r confli-olas-voto}

elsoc_long_2016_2022 %>% 
  left_join(voto_salida, by = 'idencuesta') %>% 
  filter(tipo_atricion %in% c(1, 33), 
         !is_nsnr(t11_01, t11_02, t11_03, t11_04)) %>% 
  mutate(barrio_confli = (t11_01 + t11_02 + t11_03 + t11_04)/4,
         barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0, 1, 2.75, 5)),
         labels = c("Nunca", "Pocas o algunas veces", "Muchas veces o siempre")),
         voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>% 
  sjlabelled::as_label(ola) %>% 
  prop(barrio_confli_rec == 'Muchas veces o siempre', 
       by = c(ola, voto_salida), na.rm = TRUE) %>% 
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(size = 3) +
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Conflictividad barrial alta, según ola y voto en plebiscito de salida',
          subtitle = 'Porcentaje que Muchas veces o siempre presenta Molestia o incomodidad por\nproblemas con sus vecinos')

```


```{r confli-zona}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(tipo_atricion %in% c(1, 33), 
         !is_nsnr(t11_01, t11_02, t11_03, t11_04)) %>% 
  mutate(barrio_confli = (t11_01 + t11_02 + t11_03 + t11_04)/4,
         barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0, 1, 2.75, 5)),
         labels = c("Nunca", "Pocas o algunas veces", "Muchas veces o siempre")),
         voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(barrio_confli_rec == 'Muchas veces o siempre', 
       by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  facet_wrap(~zona) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
    ggtitle('Conflictividad barrial alta, según ola y  zona geográfica',
          subtitle = 'Porcentaje que Muchas veces o siempre presenta Molestia o incomodidad por\nproblemas con sus vecinos')


```

```{r confli-olas-part}

elsoc_long_2016_2022 %>% 
  left_join(perfiles, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(tipo_atricion %in% c(1, 33), 
         !is_nsnr(t11_01, t11_02, t11_03, t11_04)) %>% 
  mutate(barrio_confli = (t11_01 + t11_02 + t11_03 + t11_04)/4,
         barrio_confli_rec = factor(cut(barrio_confli, breaks = c(0, 1, 2.75, 5)),
         labels = c("Nunca", "Pocas o algunas veces", "Muchas veces o siempre"))) %>% 
  prop(barrio_confli_rec == 'Muchas veces o siempre', 
       by = c(ola, pp_4), na.rm = TRUE) %>%
  filter(!is.na(pp_4)) %>% 
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(size = 3) +
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Conflictividad barrial alta, según ola y voto en plebiscito de salida',
          subtitle = 'Porcentaje que Muchas veces o siempre presenta Molestia o incomodidad por\nproblemas con sus vecinos')

```


#### Criminalidad barrial


```{r crim-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1) & !is_nsnr(t09_02)) %>% 
  mutate(t09_02 = factor(car::recode(t09_02, "1 = 1; 2:3 = 2; 4:5 = 3"),
                         levels = 1:3,
                         labels = c("Nunca", "Pocas o algunas veces", "Muchas veces o siempre"))) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = t09_02, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(t09_02), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  ggtitle(label = 'Criminalidad barrial, según ola',
          subtitle = 'Frecuencia con que se han producido robos o asaltos en su barrio') +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank())

```


```{r crim-olas-voto}

elsoc_long_2016_2022 %>% 
  left_join(voto_salida, by = 'idencuesta') %>% 
  filter(tipo_atricion %in% c(1), 
         !is_nsnr(t09_02)) %>% 
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>% 
  sjlabelled::as_label(ola) %>% 
  prop(t09_02 %in% 4:5, 
       by = c(ola, voto_salida), na.rm = TRUE) %>% 
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(size = 3) +
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle(label = 'Criminalidad barrial alta, según ola y voto en plebiscito de salida',
          subtitle = 'Porcentaje con frecuencia Muchas veces o Siempre con robos o asaltos en su barrio')



    
```


```{r crim-zona}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t09_02), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(t09_02 %in% 4:5, by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  facet_wrap(~zona) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Criminalidad barrial alta, según voto en plebiscito de salida y zona geográfica',
          subtitle = 'Porcentaje con frecuencia Muchas veces o Siempre con robos o asaltos en su barrio')


```

```{r crim-olas-part}

elsoc_long_2016_2022 %>% 
  left_join(perfiles, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(tipo_atricion %in% c(1), 
         !is_nsnr(t09_02)) %>% 
  prop(t09_02 %in% 4:5, by = c(ola, pp_4), na.rm = TRUE) %>%
  filter(!is.na(pp_4)) %>% 
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(size = 3) +
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, .4)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle(label = 'Criminalidad barrial alta, según ola  y patrón de participación electoral',
          subtitle = 'Porcentaje con frecuencia Muchas veces o Siempre con robos o asaltos en su barrio')
```


#### Inseguridad barrial

```{r inseg-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(t10)) %>% 
  mutate(t10 = factor(car::recode(t10, "1:2 = 1; 3 = 2; 4:5 = 3"),
                      levels = 1:3,
                      labels = c('Muy inseguro o inseguro', 'Ni seguro ni inseguro',
                                 'Seguro o muy seguro')))%>%
  sjlabelled::as_label(ola) %>% 
  prop(t10, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(t10), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
    ggtitle('Seguridad barrial, según ola',
          subtitle = '¿Que tan seguro o inseguro se siente en el barrio o vecindario donde usted vive?')


```




```{r inseg-voto}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t10), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(t10 %in% 1:2, by = c(ola, voto_salida), na.rm = TRUE)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Percepción de inseguridad barrial, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que se siente Inseguro o Muy Inseguro en su barrio')
  
```



```{r inseg-zona}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t10), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(t10 %in% 1:2, by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  facet_wrap(~zona) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Percepción de inseguridad barrial, según voto en plebiscito de salida y zona geográfica',
          subtitle = 'Porcentaje que se siente Inseguro o Muy Inseguro en su barrio')
  
```



```{r inseg-part}

elsoc_long_2016_2022 %>%
  left_join(perfiles, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t10), tipo_atricion %in% c(1, 33)) %>%  
  prop(t10 %in% 1:2, by = c(ola, pp_4), na.rm = TRUE)  %>%
  filter(!is.na(pp_4)) %>% 
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Percepción de inseguridad barrial, según perfiles de participación electoral',
          subtitle = 'Porcentaje que se siente Inseguro o Muy Inseguro en su barrio')

```

#### Confianza en vecinos


```{r conf-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(t01)) %>% 
  mutate(t01 = factor(car::recode(t01, "1:2 = 1; 3 = 2; 4:5 = 3"),
                      levels = 1:3,
                      labels = c('Muy poco o Poco', 'Algo',
                                 'Bastante o Mucho')))%>%
  sjlabelled::as_label(ola) %>% 
  prop(t01, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(t01), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 6)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
    ggtitle('Confianza en los vecinos, según ola',
          subtitle = 'En terminos generales, ¿cuanto confia usted en sus vecinos?')


```




```{r conf-voto}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t01), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(t01 %in% 4:5, by = c(ola, voto_salida), na.rm = TRUE)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Confianza en vecinos, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que confía bastante o mucho en sus vecinos')
  
```



```{r conf-zona}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t01), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(t01 %in% 4:5, by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  facet_wrap(~zona) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
    ggtitle('Confianza en vecinos, según voto en plebiscito de salida y zona geográfica',
          subtitle = 'Porcentaje que confía bastante o mucho en sus vecinos')

```



```{r conf-part}

elsoc_long_2016_2022 %>%
  left_join(perfiles, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(t01), tipo_atricion %in% c(1, 33)) %>%  
  prop(t01 %in% 4:5, by = c(ola, pp_4), na.rm = TRUE)  %>%
  filter(!is.na(pp_4)) %>% 
  ggplot(aes(y = prop, x = ola, color = pp_4, group = pp_4,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, 
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Confianza en vecinos, según perfiles de participación electoral',
          subtitle = 'Porcentaje que confía bastante o mucho en sus vecinos')

```

### Conflicto indígena


```{r conf-indigena-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(t01)) %>% 
  mutate(c06_05 = factor(car::recode(c06_05, "1:2 = 1; 3 = 2; 4:5 = 3"),
                      levels = 1:3,
                      labels = c('Nada o poca', 'Algo',
                                 'Bastante o Mucha')))%>%
  sjlabelled::as_label(ola) %>% 
  prop(c06_05, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(c06_05), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 3)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
    ggtitle('Confianza en los veMapuchescinos, según ola',
          subtitle = 'En terminos generales, ¿cuanto confia usted en los Mapuches?')


```

```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(c06_05), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(c06_05 %in% 1:2, by = c(ola, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia Mapuches, según voto en plebiscito de salida',
          subtitle = 'Porcentaje con Nada o Poca confianza en Mapuches')
  
```


```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(f09_01), !is.na(f09_02), !is.na(f09_03),
         tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop_list(f09_01 %in% 4:5, f09_02 %in% 4:5, f09_03 %in% 4:5, 
            by = c(ola, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  mutate(name = factor(name,
                       levels = glue::glue('f09_0{1:3} %in% 4:5'),
                       labels = c('Promover enseñanza de\nMapudungun en escuelas',
                                  'Reforzar politica de restitución\nde tierras a Mapuches',
                                  'Cupos reservados en el\ncongreso para el pueblo mapuche'))) %>% 
  ggplot(aes(y = prop, x = name, fill = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Acuerdo con medidas de reparación (2022), según voto en plebiscito de salida',
          subtitle = 'Porcentaje de Acuerdo o Muy de acuerdo con:')
  
```



```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(f09_01), !is.na(f09_02), !is.na(f09_03),
         tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 1,
                                 region_cod %in% c(5:8, 16) ~ 2, 
                                 region_cod %in% c(9:12, 14) ~ 3,
                                 region_cod == 13 ~ 4),
                       levels = 1:4,
                       labels = c('Norte', 'Centro', 'Sur', 'Metropolitana'))) %>%
  prop_list(f09_01 %in% 4:5, f09_02 %in% 4:5, f09_03 %in% 4:5, 
            by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo'),
         zona == 'Sur') %>% 
  mutate(name = factor(name,
                       levels = glue::glue('f09_0{1:3} %in% 4:5'),
                       labels = c('Promover enseñanza de\nMapudungun en escuelas',
                                  'Reforzar politica de restitución\nde tierras a Mapuches',
                                  'Cupos reservados en el\ncongreso para el pueblo mapuche'))) %>%
  ggplot(aes(y = prop, x = name, fill = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('Acuerdo con medidas de reparación (2022) en la zona Sur, según voto en\nplebiscito de salida',
          subtitle = 'Porcentaje de Acuerdo o Muy de acuerdo con:')
  
```



```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(c46_05), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 1,
                                 region_cod %in% c(5:8, 16) ~ 2, 
                                 region_cod %in% c(9:12, 14) ~ 3,
                                 region_cod == 13 ~ 4),
                       levels = 1:4,
                       labels = c('Norte', 'Centro', 'Sur', 'Metropolitana'))) %>%
  prop_list(c46_05 %in% 4:5, by = c(zona, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = zona, fill = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_col(position = 'dodge2') +
  geom_text(position = position_dodge(.9), 
            vjust = -.5, size = 3) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 1)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .66, direction = 1, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  ggtitle('"La nueva constitución permitirá una mejor relación entre el Estado y los pueblos\nindígenas en Chile" (2022), según voto en plebiscito de salida',
          subtitle = 'Porcentaje de Acuerdo o Muy de acuerdo')
  
```

```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(c06_05), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
         zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(c06_05 %in% 1:2, by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  facet_wrap(~zona) +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia Mapuches, según voto en plebiscito de salida y zona geográfica',
          subtitle = 'Porcentaje con Nada o Poca confianza en Mapuches')
  
```

### Conflicto migratorio



```{r conf-migratorio-olas}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(r16), ola %in% 4:6) %>% 
  mutate(r16 = factor(car::recode(r16, "1:2 = 1; 3 = 2; 4:5 = 3"),
                      levels = 1:3,
                      labels = c('Nada o poca', 'Algo',
                                 'Bastante o Mucha')))%>%
  sjlabelled::as_label(ola) %>% 
  prop(r16, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(r16), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 3)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
    ggtitle('Confianza en los migrantes, según ola',
          subtitle = 'En terminos generales, ¿cuanto confia usted en los Peruanos, Haitianos o Venezolanos que viven en Chile?')

```


```{r conf-migratorio-nacion}

elsoc_long_2016_2022 %>% 
  filter(tipo_atricion %in% c(1, 33) & !is_nsnr(r16), ola %in% 4:6) %>% 
  mutate(r16 = factor(car::recode(r16, "1:2 = 1; 3 = 2; 4:5 = 3"),
                      levels = 1:3,
                      labels = c('Nada o poca', 'Algo',
                                 'Bastante o Mucha')))%>%
  sjlabelled::as_label(ola) %>% 
  prop(r16, by = ola, na.rm = TRUE) %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(r16), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_fill_viridis_d(end = .85) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5),
            size = 3, 
            color = rep(c('black', 'white', 'white'), 3)) + 
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top', 
        legend.title = element_blank()) +
    ggtitle('Confianza en los migrantes, según ola',
          subtitle = 'En terminos generales, ¿cuanto confia usted en los Peruanos, Haitianos o Venezolanos que viven en Chile?')

```

```{r}

elsoc_long_2016_2022 %>%
  filter(!is.na(r16), tipo_atricion %in% c(1, 33), ola %in% 4:6) %>%  
  sjlabelled::as_label(ola, cuestion_mig) %>%
  prop(r16 %in% 1:2, by = c(ola, cuestion_mig), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = cuestion_mig, group = cuestion_mig,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia inmigrantes, según nacionalidad de migrantes',
          subtitle = 'Porcentaje con Nada o poca confianza en inmigrantes')
  
```



```{r}

elsoc_long_2016_2022 %>%
  filter(!is.na(r16), tipo_atricion %in% c(1, 33), ola %in% 4:6) %>%  
  sjlabelled::as_label(ola, cuestion_mig) %>%
  mutate(zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>% 
  prop(r16 %in% 1:2, by = c(ola, cuestion_mig, zona), na.rm = T)  %>%
  ggplot(aes(y = prop, x = ola, color = cuestion_mig, group = cuestion_mig,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  facet_wrap(~zona) +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(end = .75, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia inmigrantes, según nacionalidad de migrantes y zona geográfica',
          subtitle = 'Porcentaje con Nada o poca confianza en inmigrantes')
  
```

```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(r16), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros")),
           zona = factor(case_when(region_cod %in% c(1:4, 15) ~ 'Norte',
                                 region_cod %in% c(5:8, 16) ~ 'Centro',
                                 region_cod %in% c(9:12, 14) ~ 'Sur',
                                 region_cod == 13 ~ 'Metropolitana'))) %>%
  prop(r16 %in% 1:2, by = c(ola, voto_salida, zona), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  facet_wrap(~zona) +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .8)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia inmigrantes, según voto en plebiscito de salida',
          subtitle = 'Porcentaje con Nada o poca confianza en inmigrantes')
  
```




```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(r16), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(r16 %in% 1:2, by = c(ola, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Desconfianza hacia migrantes, según voto en plebiscito de salida',
          subtitle = 'Porcentaje que confía nada o casi nada en migrantes')
  
```


```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(r12_04), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(r12_04 %in% 4:5, by = c(ola, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Amenaza realista, según voto en plebiscito de salida',
          subtitle = 'De acuerdo o Muy de acuerdo con "Con la llegada de migrantes aumenta el desempleo"')
  
```


```{r}

elsoc_long_2016_2022 %>%
  left_join(voto_salida, by = 'idencuesta') %>% 
  sjlabelled::as_label(ola) %>%
  filter(!is.na(r12_03), tipo_atricion %in% c(1, 33)) %>%  
  mutate(voto_salida = factor(car::recode(voto_salida, "1 = 1; 2 = 2; 3:5 = 3"), 
                       levels = 1:3,
                       labels = c("Apruebo", "Rechazo", "Otros"))) %>%
  prop(r12_03 %in% 4:5, by = c(ola, voto_salida), na.rm = T)  %>%
  filter(!is.na(voto_salida), voto_salida %in% c('Apruebo', 'Rechazo')) %>% 
  ggplot(aes(y = prop, x = ola, color = voto_salida, group = voto_salida,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  geom_point(size = 1.75) + 
  geom_line() + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .75)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = .1, end = .66, option = 'viridis') +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) + 
  ggtitle('Amenaza simbólica, según voto en plebiscito de salida',
          subtitle = 'De acuerdo o Muy de acuerdo con "Con la llegada de migrantes Chile pierde su identidad"')
  
```
