
# Conclusiones

A partir del contraste sistemático de las preferencias, actitudes y comportamientos de las personas que participan regularmente en las elecciones (Votantes habituales) con aquellas que participan en ocasiones (Votantes reactivos), y particularmente con aquellas que regularmente no participan (No votantes) se pueden establecer cuatro importantes regularidades. 

En primer lugar, los no votantes tienden a ser marcadamente menos politizados que los votantes reactivos, y más aún, que los votantes habituales. Los primeros registran niveles de politización muy descendidos en múltiples indicadores tales como el interés en temas políticos, la frecuencia de conversación y discusión, la propensión a identificarse con categorías ideológicas y partidarias, los niveles de participación, entre otros. 

Segundo, los no votantes tienden a ser más conservadores que los votantes habituales en sus orientaciones valóricas, particularmente sobre temas de moralidad sexual (aborto y adopción entre parejas del mismo sexo). En una línea similar, se observa una valoración más negativa del impacto económico y cultural de la inmigración entre el grupo de los no votantes que entre los votantes habituales, así como niveles de confianza más bajos hacia el pueblo mapuche. En contraste, las diferencias entre grupos se reducen cuando se tratan de temas socioeconómicos como el rol del Estado en educación o en pensiones. 

Tercero, los niveles de apoyo al régimen democrático entre no votantes, en contraste con los votantes habituales (y en menor medida con votantes reactivos), son comparativamente bajos, al tiempo que los niveles de indiferencia hacia el régimen de gobierno son particularmente altos. En contraste, formas de apoyo político más específicas, como satisfacción con el funcionamiento de la democracia o confianza en instituciones políticas, se encuentran muy descendidos en los tres grupos.

Cuarto, las preferencias políticas de los no votantes, sintetizadas a través de su auto-posicionamiento en la escala de izquierda-derecha, son más inestables en el tiempo que entre votantes habituales o reactivos, particularmente entre los segmentos de la muestra que se identifican en algunas olas con la izquierda o la derecha. Esto es un atributo importante, porque si bien hoy los no votantes adoptan posiciones más conservadoras en algunas temáticas, es también cierto que indican una mayor volatilidad en el tiempo, probablemente debido a su menor politización e involucramiento con temas políticos.

De lo anterior, podemos concluir que los resultados previos son inconsistentes con la tesis de que una gran cantidad de votantes optó por la opción del Rechazo en el Plebiscito de Salida motivados por desinformación y fake news, y en especial, entre el segmento de ciudadanos que no había votado en elecciones anteriores. Parece más probable el hecho de que se introdujo en el electorado, gracias al voto obligatorio con inscripción automática, un segmento de gran proporción que se perfila menos progresista que los antiguos votantes en lo referido a los temas asociados en temas de moral sexual, inmigración e interculturalidad. 